// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdhDrYxYj4n30sJUDu-AKe9Fh3DXICVnc',
    appId: '1:539537376020:android:559bbf53a826b19a8ab801',
    messagingSenderId: '539537376020',
    projectId: 'chitchat-1abd2',
    databaseURL: 'https://chitchat-1abd2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chitchat-1abd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9smzI10jTh1T2CtTicg9ZSsSBrvmIzjA',
    appId: '1:539537376020:ios:f3c3727900fabc5b8ab801',
    messagingSenderId: '539537376020',
    projectId: 'chitchat-1abd2',
    databaseURL: 'https://chitchat-1abd2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chitchat-1abd2.appspot.com',
    androidClientId: '539537376020-17l8mdaa3rrfb685fk7n91bhn7u4a5em.apps.googleusercontent.com',
    iosClientId: '539537376020-3lf92uhm4t5v3sudshagb0ld8em40q59.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );
}
